#!/usr/bin/env bash
set -euo pipefail

# changelog.sh — Generate CHANGELOG.md from git history
# Usage: bash changelog.sh [--repo /path/to/repo] [--output CHANGELOG.md]

REPO="${PWD}"
OUTPUT="${PWD}/CHANGELOG.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Usage: $0 [--repo path] [--output path]"; exit 1 ;;
  esac
done

if [[ ! -d "${REPO}/.git" ]]; then
  echo "❌ Not a git repository: ${REPO}"
  exit 1
fi

cd "${REPO}"

LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
SINCE_ARG="${LAST_TAG}..HEAD"

if [[ -n "${LAST_TAG}" ]]; then
  echo "Since tag: ${LAST_TAG}"
else
  echo "No tags found — using all commits"
  SINCE_ARG="HEAD"
fi

ADDED=(); FIXED=(); CHANGED=(); REMOVED=(); OTHER=()

while IFS='|' read -r hash subject; do
  prefix=$(echo "${subject}" | sed -nE 's/^([a-z]+)(\([^)]*\))?!?:.*/\1/p')
  desc=$(echo "${subject}" | sed -E 's/^[a-z]+(\([^)]*\))?!?:\s*//i')
  case "${prefix}" in
    feat|feature)   ADDED+=("${desc}") ;;
    fix)            FIXED+=("${desc}") ;;
    refactor|perf|style|chore|docs|test|ci|build)
                    CHANGED+=("${desc} (${prefix})") ;;
    revert|remove)  REMOVED+=("${desc}") ;;
    *)              OTHER+=("${subject}") ;;
  esac
done < <(git log "${SINCE_ARG}" --oneline --no-decorate --format="%h|%s" 2>/dev/null)

DATE=$(date +%Y-%m-%d)
VERSION="${LAST_TAG:-0.1.0}"

{
  echo "# Changelog"
  echo ""
  echo "## [${VERSION}] - ${DATE}"
  echo ""
  if [[ ${#ADDED[@]} -gt 0 ]]; then
    echo "### Added"; for item in "${ADDED[@]}"; do echo "- ${item}"; done; echo ""
  fi
  if [[ ${#FIXED[@]} -gt 0 ]]; then
    echo "### Fixed"; for item in "${FIXED[@]}"; do echo "- ${item}"; done; echo ""
  fi
  if [[ ${#CHANGED[@]} -gt 0 ]]; then
    echo "### Changed"; for item in "${CHANGED[@]}"; do echo "- ${item}"; done; echo ""
  fi
  if [[ ${#REMOVED[@]} -gt 0 ]]; then
    echo "### Removed"; for item in "${REMOVED[@]}"; do echo "- ${item}"; done; echo ""
  fi
  if [[ ${#OTHER[@]} -gt 0 ]]; then
    echo "### Uncategorized"; for item in "${OTHER[@]}"; do echo "- ${item}"; done; echo ""
  fi
  echo "---"
  echo "_Generated by [changelog.sh](https://github.com/kingjinxh/claude-builders-bounty)_"
} > "${OUTPUT}"

echo "CHANGELOG.md generated -> ${OUTPUT}"
echo "   ${#ADDED[@]} Added | ${#FIXED[@]} Fixed | ${#CHANGED[@]} Changed | ${#REMOVED[@]} Removed"
